### ISSUE TITLE
arbitrary header support for internal tests

### ISSUE THREAD

**Issue by ybrs** [Hipo/http-checks#3]
something like,

```
    tryprism.production:
        url: http://127.0.0.1/user/login
        headers:
             - Host: hipo.biz
```

so we can run this internally, and test subdomains without messing up with /etc/hosts
